import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { EmptyState } from '@/features/dashboard/components/empty-state'

export function SummaryCard({ summary }: { summary: string | null }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Summary</CardTitle>
        <CardDescription>
          Generated by ElevenLabs post-call analysis.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {summary ? (
          <p className="text-sm leading-relaxed">{summary}</p>
        ) : (
          <EmptyState
            title="No summary"
            description="The agent didn't generate a transcript summary for this conversation."
          />
        )}
      </CardContent>
    </Card>
  )
}
